version: "3"

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: psql
      POSTGRES_PASSWORD: psql
      PGPASSWORD: psql
      POSTGRES_DB: todo
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
